// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG1FBKe4MtWuk3g1W4pX9O6b9XhM0BusM',
    appId: '1:144205958158:web:3b8a66241685652698805f',
    messagingSenderId: '144205958158',
    projectId: 'shopapp-e5f12',
    authDomain: 'shopapp-e5f12.firebaseapp.com',
    storageBucket: 'shopapp-e5f12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6tji7m9DbhtIzNW3h9nAp6roNHJG5Jkg',
    appId: '1:144205958158:android:864a2f0ba0e58ad098805f',
    messagingSenderId: '144205958158',
    projectId: 'shopapp-e5f12',
    storageBucket: 'shopapp-e5f12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTaASQgLBy_Ms0j2HLzIZ-KtuH2UkgrgA',
    appId: '1:144205958158:ios:644d5df83d7efbca98805f',
    messagingSenderId: '144205958158',
    projectId: 'shopapp-e5f12',
    storageBucket: 'shopapp-e5f12.firebasestorage.app',
    androidClientId: '144205958158-9dhfo7q8hh20dum3jc13ao89022d5hjk.apps.googleusercontent.com',
    iosClientId: '144205958158-mk2mqq55u5ffj69ks09c2kfi4vo0sujd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ytEcommerceAdminPanel',
  );
}
